### ISSUE TITLE
Heads filtering not working in 1.21

### ISSUE THREAD

**Issue by BEMZ01** [oddlama/vane#268]
/heads command successfully shows the menu - however upon pressing the filter button to open the Anvil search GUI, the menu closes, and an error is logged to the console.

```
[14:30:11 INFO]: BEMZlabs issued server command: /heads
[14:30:13 ERROR]: Could not pass event InventoryClickEvent to vane-core v1.15.0
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.view.CraftAnvilView org.oddlama.vane.core.menu.AnvilMenu$AnvilContainer.getBukkitView()'
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.AnvilMenu.<init>(AnvilMenu.java:28) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.MenuFactory.anvil_string_input(MenuFactory.java:41) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.HeadFilter.open_filter_settings(HeadFilter.java:26) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.GenericSelector.lambda$create$991af3dc$1(GenericSelector.java:96) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.MenuItem.click(MenuItem.java:90) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.Menu.click(Menu.java:173) ~[vane-core-1.15.0.jar:?]
	at vane-core-1.15.0.jar/org.oddlama.vane.core.menu.MenuManager.on_inventory_click(MenuManager.java:164) ~[vane-core-1.15.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor46.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-106-3a47518]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-106-3a47518]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-106-3a47518]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-106-3a47518]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-106-3a47518]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by oddlama** [comment]
This is because you are using vane 1.15.0 (for MC 1.21.1) on minecraft 1.21.
